# 开发环境相关配置在这里写，由spring.profiles.active控制
it235:
  tenant:
    enable: false
  mysql:
    username: root
    password: TFSQL987
    url: 47.92.230.43:3306
    dbname: wzrtest
  redis:
    host: 47.92.230.43
    password: UATTiFangEDU123
    port: 6379
