server:
  port: 7050
spring:
  application:
    name: it235-boot-zipkin-producer
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://${it235.mysql.url}/${it235.mysql.dbname}?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=yourdb&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${it235.mysql.username}
    password: ${it235.mysql.password}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5  # 初始化大小
      min-idle: 5  # 最小
      max-active: 100  # 最大
      max-wait: 60000  # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: select 'x'
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false  # 在连接归还到连接池时是否测试该连接
      filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20

      # druid web config
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: knifeboot
        login-password: knifeboot
  redis:
    host: ${it235.redis.host}
    password: ${it235.redis.password}
    port: ${it235.redis.port}
    database: 1 # 使用库 1
    timeout: 60s
    lettuce: # lettuce基于netty，线程安全，支持并发
      pool:
        max-active: 50
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  zipkin:
    base-url: http://47.92.230.43:9411/
    enabled: true
    discovery-client-enabled: false
    sender:
      type: web
    service:
      name: ${spring.application.name}
    compression:
      enabled: true
  sleuth:
    sampler:
      probability: 1
# mybatis-plus配置
mybatis-plus:
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true
    # Mapper.xml路径，注意pom.xml中需要开启xml文件的编译
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/it235/cloud/example/**/mapper/xml/*Mapper.xml
  # xml中alias的匹配
  type-aliases-package: com.it235.cloud.example.**.entity
  # 图标关闭
  global-config:
    banner: false
